---
title: "MIL_explore"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

read data, change date column data type
```{r}

library(tidyverse)

data <- read_csv("MIL_50years_R.csv")

colnames(data) <- c("id", "duration", "sensor_number", "sensor_type", "year", "month", "day", "date", "obs_date", "value", "flag", "units")

as.Date(data$date, format = "%m-%d-%y")


inflow <- data %>% 
  filter(sensor_type == "INFLOW")
as.Date(inflow$date, format = "%m-%d-%y")

outflow <- data %>% 
  filter(SENSOR_TYPE == "OUTFLOW")
as.Date(outflow$DATE, format = "%m-%d-%y")

release<- data %>% 
  filter(SENSOR_TYPE == "REL SCH")
as.Date(release$DATE, format = "%m-%d-%y")

storage<- data %>% 
  filter(SENSOR_TYPE == "STORAGE")
as.Date(storage$DATE, format = "%m-%d-%y")



```



test run?
```{r}

plot <- ggplot(data = inflow, aes(x = obs_date, y = value))+
  geom_line()+
  geom_smooth()+
  theme_minimal()+
  scale_y_continuous(limits = c(0,50000))

plot


```







